---
- hosts: localhost
  user: "{{ mac_workstation_user }}"
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - { role:  rvm_io.rvm1-ruby, tags: ruby, become: true }

  tasks:
    - include: tasks/ansible-setup.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false

    - name: Generate SSH Key
      command: ssh-keygen -t rsa -b 8192 -N '' -f ~/.ssh/id_rsa
        creates=~/.ssh/id_rsa

    - include: tasks/prezto.yml
    - include: tasks/janus.yml
    - include: tasks/ruby.yml
