---
- hosts: localhost
  user: tyler
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false

    # This should be a role...
    - name: Clone Prezto
      git:
        repo: https://github.com/sorin-ionescu/prezto
        dest: ~/.zprezto

    - name: Link Prezto Files
      file:
        state: link
        src: ~/.zprezto/runcoms/{{ item }}
        path: ~/.{{ item }}
      with_items:
        - zlogin
        - zlogout
        - zprofile
        - zshenv

    # This should be a role...
    - name: Clone Janus
      git:
        repo: https://github.com/carlhuda/janus
        dest: ~/.vim

    - name: Install Janus
      command: rake chdir=~/.vim
